sudo: required

language: c

os:
  - linux

services:
  - docker

cache:
  directories:
    - $HOME/build

stages:
  - pre-build
  - build

jobs:
  include:
    - stage: pre-build
      script:
        - docker pull kaizhang/centos-haskell-stack
        - docker run
          -v $HOME/build:/root/.stack
          -v `pwd`:/source:rw
          kaizhang/centos-haskell-stack
          /bin/bash -c
          "cd source && stack build --only-dependencies --allow-different-user"
    - stage: build
      script:
        - docker pull kaizhang/centos-haskell-stack
        - docker run
          -v $HOME/build:/root/.stack
          -v `pwd`:/source:rw
          kaizhang/centos-haskell-stack
          /bin/bash -c
          "cd source &&
          stack install --allow-different-user &&
          mv /root/.local/bin/taiji /source/taiji-Linux-x86_64"
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file: 
          - taiji-Linux-x86_64
        on:
          tags: true