sudo: required

language: c

os:
  - linux

services:
  - docker

cache:
  directories:
    - $HOME/build

stages:
  - pre-build
  - build

jobs:
  include:
    - stage: pre-build
      script:
        - docker pull kaizhang/centos-haskell-stack
        - docker run
          -v $HOME/build:/root/.stack
          -v `pwd`:/source:rw
          kaizhang/centos-haskell-stack
          /bin/bash -c
          "cd source && stack install bioinformatics-toolkit --allow-different-user"
        - chmod -R 777 $HOME/build
    - stage: build
      script:
        - docker pull kaizhang/centos-haskell-stack
        - docker run
          -v $HOME/build:/root/.stack
          -v `pwd`:/source:rw
          kaizhang/centos-haskell-stack
          /bin/bash -c
          "cd source && stack build --allow-different-user &&
          mv $(stack path --local-install-root --allow-different-user)/bin/taiji /source/taiji-Linux-x86_64"
        - chmod -R 777 $HOME/build
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_TOKEN
        file: 
          - taiji-Linux-x86_64
        on:
          tags: true
