resolver: nightly-2019-05-25

packages:
- '.'

extra-deps:

#- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
#  commit:  b1ae0189ba8d1c90f7d534a350bf3d649453f6f2
- '../Taiji-utils'

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  b9814899ac5d8322bf1e8e04b48712472e807df7

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  470d1c09c8b8ecc64ced5f085c87cc66d70f8b9d

#- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
#  commit:  f39562579970b24c38f0c9f308eb9971162bff0f
- '../Taiji-RNA-seq'

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  60b3ed7428eb2da18340f27c4c34a90a703082b9

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  4da1197a49d3866d5a5cbfbb5ede696dbeadc046

#- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
#  commit:  e39da8a35967d11289d999f382f6c9a2a0db1a6b
- '../Taiji-scATAC-seq'

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  38d248c9a77132198b765dd41a30a04b1c12e2ce
  subdirs:
      - bioinformatics-toolkit

- bbi-0.1.1
- drmaa-0.3.0
- clustering-0.4.1
- jmacro-0.6.16

- git:     https://github.com/haskell-distributed/distributed-static.git
  commit:  d34b5139a0c349fbda6ffea5fbbe960c3c91aeb1
- git:     https://github.com/haskell-distributed/network-transport-tcp.git
  commit:  5a08e32c73093c1338c09a17a95c456568394d48
- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
- distributed-process-monad-control-0.5.1.3

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  c50abcb328757a07ee6934f6ed7f8df853325de8
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
