resolver: nightly-2019-05-25
#resolver: nightly-2020-01-17

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  ccb65aae38764cd176ae8f79a9869a1d1f117234

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  c1f83502718bb4dff028eaab9493e79ce6634f1b

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  e4dd0b2dba06015b960287e18a01072badbcbb0a

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  e92cb6ce074f612f6152f6970a20f0acebe9c326

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  3bd264eb1cd24ec114b7fa077914334349fe6be1

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  60e02353a5667d2dde41de9cc34e2c655d135ac0

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  caca3d02d391382ef6a16e49b9bf088116bf40c0

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- git:     https://github.com/kaizhang/ChromVAR.git
  commit:  d65357474b714e1eed4867b528fbb6995b13b000

- bioinformatics-toolkit-0.9.3.1
- haskell-igraph-0.8.0

- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.16
- matrix-sized-0.0.3

- git:     https://github.com/haskell-distributed/distributed-static.git
  commit:  d34b5139a0c349fbda6ffea5fbbe960c3c91aeb1
- git:     https://github.com/haskell-distributed/network-transport-tcp.git
  commit:  5a08e32c73093c1338c09a17a95c456568394d48
- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
- distributed-process-monad-control-0.5.1.3

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  2b88b7f99f8c4555919a9746782984545d319006
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
