resolver: lts-18.12

packages:
- '.'

flags:
  cryptonite:
    use_target_attributes: false
  matrix-sized:
    parallel: false

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  f5e009cf7a9a683f7e43bf97fb33c758ba13d97b

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  90f242992001be3672ddc2c1749beff432bbc5f3

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  12d62074c50f746482c3c2db4e5b47bc43803a60

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  a567e632e1167d7105974e1acf87be9f356fc494

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  ba7a073b56bf4ca60a227d70b4508f2f83a57d16

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  0362dc0fc0024ff474f4d582d048852444eac5b9

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  6e912364ddce0f7ddcaae7938cd9696aac4937ca

- git:     https://github.com/Taiji-pipeline/Taiji-fusion.git
  commit:  a2ef0b3c162028ba1bd89c7f151b3e703f4cde8d

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  a2fcc435fc752152f06f14e0cfa56153fa0b7d02

- git:     https://github.com/kaizhang/ChromVAR.git
  commit:  d64dd55579c8db9625028065b4cb3314e8f0c4a9

- git:     https://github.com/kaizhang/matrix-sized.git
  commit:  aed69651b2da5ca4c9076c8c4d981b876932e5b8

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  d790e030e6e08b04dc0971221b6054d6700d82e7

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  463cb8d16230a0777072e8793338b89a7c420487
  subdirs:
      - bioinformatics-toolkit

- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.17

- git:     https://github.com/Taiji-pipeline/distributed-process.git
  commit:  e143f6bce9d7f1e13b0d12f11763f6f24d2da4df
- distributed-process-monad-control-0.5.1.3
- network-transport-tcp-0.8.0
- distributed-static-0.3.9

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  ee510340b54f4e2c416cc6e121c767885abce374
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
