resolver: lts-17.4

packages:
- '.'

flags:
  cryptonite:
    use_target_attributes: false

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  3a42e300cc9c98a18647964a59bada44cfedee2b

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  2306c271f1147b2825aa4d7ec17bcacf01682bd4

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  62e821383792ff5057a959e1082369adc79e26b6

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  7f34241225f9033a96050bde6ba958b8519041af

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  9a10f90ba67ccadcd2cbe24ef3dd373e64327208

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  59449752fa4ec60f269bbe9d13d8a19bb591d17b

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  2bbde0991a6c4b5767974ac509654c982230357d

- git:     https://github.com/Taiji-pipeline/Taiji-fusion.git
  commit:  a2ef0b3c162028ba1bd89c7f151b3e703f4cde8d

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- git:     https://github.com/kaizhang/ChromVAR.git
  commit:  d64dd55579c8db9625028065b4cb3314e8f0c4a9

- git:     https://github.com/kaizhang/matrix-sized.git
  commit:  c58c2ccae708226faab1dce9545364a39f5a2076

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  ad655dee4754ea4c224b85bc24100e4d5ad69042

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  426ee4e6ddb620579d4483fb692ed454077b807b
  subdirs:
      - bioinformatics-toolkit

- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.17

- git:     https://github.com/patrickt/distributed-process.git
  commit:  645bc55c1b0b0d18227d1fc093379967c74af669
- distributed-process-monad-control-0.5.1.3
- network-transport-tcp-0.8.0
- distributed-static-0.3.9

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  40df4c8c651e79db3dc8507224a30b978d28ced0
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote