resolver: nightly-2019-05-25

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  f796c18ff3998713c2485d67f74c5e96367d285d

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  50d65bc42b9331badc00bf387cecfbe008ad37e9

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  470d1c09c8b8ecc64ced5f085c87cc66d70f8b9d

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  0b184782b70c4200c4be829e92c3fed6d7de7572

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  e33ca8295342412ee4d32bfa4f0a7815db4221ce

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  6043a6572730ce02ee535119c35b22c5f227518a

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  0079329d422dec161dfbbfd6e44b94942bdbd077

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- bioinformatics-toolkit-0.9.0

- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.16

- git:     https://github.com/haskell-distributed/distributed-static.git
  commit:  d34b5139a0c349fbda6ffea5fbbe960c3c91aeb1
- git:     https://github.com/haskell-distributed/network-transport-tcp.git
  commit:  5a08e32c73093c1338c09a17a95c456568394d48
- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
- distributed-process-monad-control-0.5.1.3

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  ca5f37411e73c9066f67f7fe65f4a341946c7dfd
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
