resolver: nightly-2019-05-25
#resolver: nightly-2020-01-17

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  4811e87ff6ce22a3ca3b0c7a19547f18b976274d

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  7db3d5030f85944a1151cc9654676f2c8b151de7

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  07e7828d5ab7b097087d60bc716729dc88741279

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  e92cb6ce074f612f6152f6970a20f0acebe9c326

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  afd7b0d98a420afa14ee3fcdd103ca9b4f171f6a

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  93f70a4d80c6e3b2878ff27be150648876d5ba9c

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  6e7ad0d514324ccbe51ecf97164460d082ca803f

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- git:     https://github.com/kaizhang/ChromVAR.git
  commit:  5c252643a180bafaf80410767b9afabe8d825104

- git:     https://github.com/kaizhang/matrix-sized.git
  commit:  b7d1a52a09138366d92fb7c778257baaac9c6cc8

- bioinformatics-toolkit-0.9.3.1
- haskell-igraph-0.8.0

- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.16

- git:     https://github.com/haskell-distributed/distributed-static.git
  commit:  d34b5139a0c349fbda6ffea5fbbe960c3c91aeb1
- git:     https://github.com/haskell-distributed/network-transport-tcp.git
  commit:  5a08e32c73093c1338c09a17a95c456568394d48
- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
- distributed-process-monad-control-0.5.1.3

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  2b88b7f99f8c4555919a9746782984545d319006
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
