resolver: nightly-2019-05-25

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  f796c18ff3998713c2485d67f74c5e96367d285d

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  4b2feb52eb62dde1c26bb4a7e9c4d5456f6034b5

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  470d1c09c8b8ecc64ced5f085c87cc66d70f8b9d

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  384c714206e192e743e3c6de50a74f29fd62cf4e

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  fd5df5fa73946d4e4e836bb46d539248f983cd4d

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  b5d02b0aef22b11f60997f4e86ff67e512d4aa2f

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  75b79eb117251dc595712d41ef2f310f8301d5a1

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- bioinformatics-toolkit-0.9.1

- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.16

- git:     https://github.com/haskell-distributed/distributed-static.git
  commit:  d34b5139a0c349fbda6ffea5fbbe960c3c91aeb1
- git:     https://github.com/haskell-distributed/network-transport-tcp.git
  commit:  5a08e32c73093c1338c09a17a95c456568394d48
- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
- distributed-process-monad-control-0.5.1.3

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  2b88b7f99f8c4555919a9746782984545d319006
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
