resolver: nightly-2019-05-25
#resolver: nightly-2020-01-17

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  d0cfb760be0ba61edef7e2eda240be0b928203d4

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  f06aebdcda6cc5ee814aa02857455d6a2da6fc43

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  07e7828d5ab7b097087d60bc716729dc88741279

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  7f34241225f9033a96050bde6ba958b8519041af

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  9a10f90ba67ccadcd2cbe24ef3dd373e64327208

#- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
#  commit:  4412bdb8aa76b0ea8f8eddaf5bd5ca6c5f15e24d
- '../Taiji-scRNA-seq'

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  17fde35d9fa76a882cc7dee7774f14d12b88281c

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- git:     https://github.com/kaizhang/ChromVAR.git
  commit:  d64dd55579c8db9625028065b4cb3314e8f0c4a9

- git:     https://github.com/kaizhang/matrix-sized.git
  commit:  c58c2ccae708226faab1dce9545364a39f5a2076

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  b13e630aaea6c26c918446c3495c8b54c3bd8257
  subdirs:
      - bioinformatics-toolkit
#- bioinformatics-toolkit-0.9.3.1

- haskell-igraph-0.8.0
- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.16

- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
- distributed-process-monad-control-0.5.1.3
- network-transport-tcp-0.7.0
- distributed-static-0.3.9

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  f16e9ab5ce3abb37da259ab92d68cbf45020d241
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
