resolver: nightly-2019-05-11

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  af37677ff940cd2b50090e7921b0bf8365e45fda

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  3b756e3ff0cb31c4e9ed8a1cc8d24c2ea6951af6

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  5fd7472babf427606058594c089abf689b7b89f4

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  bfa057c054238af21824da74164b227fcc8dae85

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  75cbefb237db94d27b35bef307d02bb31889490f

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  d2eaae2841d0b2a292309bf510252b5fc69ebe75

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  a5194a7be53d3961db37b496fa620b34a21713de

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  75a8a813410a5c8267a59794c875f4d277ceb1be
  subdirs: 
    - bioinformatics-toolkit

- git:     https://github.com/kaizhang/bbi.git
  commit:  2681f05915aacae99d68e59c02009e44c571933e

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- drmaa-0.2.0
- clustering-0.4.1
- SciFlow-0.6.2