resolver: nightly-2019-05-25
#resolver: nightly-2020-01-17

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  bcb89db69e6b9ec4fbedcdd40a394162768ac3d4

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  e4a33d287fe052dc53032407e113ce031384f09f

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  32182f48c77eedea0d9e6058c4227b341472a145

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  7f34241225f9033a96050bde6ba958b8519041af

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  9a10f90ba67ccadcd2cbe24ef3dd373e64327208

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  a66a1fa85a1f16827a3450f90107e91f77be137e

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  2be17cbaa5c32e996d0ad05582f36e3b22a8979d

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- git:     https://github.com/kaizhang/ChromVAR.git
  commit:  d64dd55579c8db9625028065b4cb3314e8f0c4a9

- git:     https://github.com/kaizhang/matrix-sized.git
  commit:  c58c2ccae708226faab1dce9545364a39f5a2076

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  426ee4e6ddb620579d4483fb692ed454077b807b
  subdirs:
      - bioinformatics-toolkit

- haskell-igraph-0.8.0
- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.16

- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
- distributed-process-monad-control-0.5.1.3
- network-transport-tcp-0.7.0
- distributed-static-0.3.9

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  f16e9ab5ce3abb37da259ab92d68cbf45020d241
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote