resolver: nightly-2019-05-25

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/Taiji-utils.git
  commit:  57922605368ad1d5f76431deb2dbf4326664fdba

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  88f1b1a859fbf38880f871a926c9237009a9de4c

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  470d1c09c8b8ecc64ced5f085c87cc66d70f8b9d

- git:     https://github.com/Taiji-pipeline/Taiji-RNA-seq.git
  commit:  614902c8dd26cabb9f5e08c28e8000be99998ee3

- git:     https://github.com/Taiji-pipeline/Taiji-ATAC-seq.git
  commit:  14a8653a9109cc7f4192b0c6f9300421a453620c

- git:     https://github.com/Taiji-pipeline/Taiji-scRNA-seq.git
  commit:  ed5050a6b76c4df7193c1f9f34539f5059ddebbd

- git:     https://github.com/Taiji-pipeline/Taiji-scATAC-seq.git
  commit:  cab413901fde4e7deb46912363cc1fbaa7676a27

- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  e9db8aad4ca005257a464a5eff0e5ff15aa761b2

- git:     https://github.com/kaizhang/HsHTSLib.git
  commit:  c116cfa29e33d3142a6cb502f1dc4c02066d0aa9

- bioinformatics-toolkit-0.9.0

- bbi-0.1.1
- clustering-0.4.1
- jmacro-0.6.16

- git:     https://github.com/haskell-distributed/distributed-static.git
  commit:  d34b5139a0c349fbda6ffea5fbbe960c3c91aeb1
- git:     https://github.com/haskell-distributed/network-transport-tcp.git
  commit:  5a08e32c73093c1338c09a17a95c456568394d48
- git:     https://github.com/haskell-distributed/distributed-process.git
  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
- distributed-process-monad-control-0.5.1.3

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  ca5f37411e73c9066f67f7fe65f4a341946c7dfd
  subdirs:
      - SciFlow
      - SciFlow-app
      - SciFlow-remote
